# Site
title: Vergilius
description: Start of Something
url: https://vergilius.xyz
logo: slykuiper.png                                       # Site logo
locale: en_US

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
#google-analytics: UA-XXXXX-Y

# Social Links
email:             corbin@slykuiper.com
#google.plus:        username
twitter:            slykuiper
#facebook:           slykuiper
#github:             slykuiper
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          slykuiper
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
dribbble:          slykuiper
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           slykuiper

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
